version: 2.1

orbs:
  node: circleci/node@4.7
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
  # build-and-push-image:
  #   docker:
  #     - image: cimg/node:12.16
  #   environment:
  #     ECR_URL: 965398552090.dkr.ecr.ap-northeast-1.amazonaws.com
  #     ECR_REPO: simple-note-react
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.7
  #     - run:
  #         name: Install Docker
  #         command: curl -fsSL https://get.docker.com | sh -
  #     - node/install-packages:
  #         # If you are using yarn, change the line below from "npm" to "yarn"
  #         pkg-manager: npm
  #     - aws-ecr/build-and-push-image:
  #         checkout: false
  #         account-url: ECR_URL
  #         region: AWS_DEFAULT_REGION
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         path: .
  #         repo: "${ECR_REPO}"
  #         tag: "${CIRCLE_SHA1}"

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - build-and-test
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test:
      #     version: "12.16" # "16.10"
      #     pkg-manager: npm
      - aws-ecr/build-and-push-image:
          requires:
            - build-and-test
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: .
          repo: "${AWS_ECR_REPO_NAME}"
          tag: "${CIRCLE_SHA1}"
